apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
spec:
  selector:
    matchLabels:
      app: python-backend
  replicas: 4
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: 00420/backend:latest
        ports:
        - containerPort: 5000
