apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-backend
  name: python-backend
spec:
  selector:
    app: python-backend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer
