apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-react-app
  name: demo-react-app
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: demo-react-app
  type: LoadBalancer
