name: Hello World Python CI

on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - main 

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
    - name: Task 1 
      uses: actions/checkout@v2 

    - name: Task 2 
      uses: actions/setup-python@v2 
      with: 
        python-version: '3.8' 

    - name: Install Task 
      run: | 
        python -m pip install --upgrade pip 

    - name: Task Flake8 
      run: | 
        pip install flake8 
        flake8 . 

    - name: Run 
      run: | 
        pip install pytest 
        pytest
